version: '3.8'

name: uss-queue

services:
  uss-queue-server:
    container_name: uss-queue-server
    image: ${DOCKER_HUB_USERNAME}/uss-queue-server:prod
    ports:
      - "8383:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - uss-prod
    volumes:
      - ./logs:/var/log/spring
    depends_on:
      uss-queue-redis:
        condition: service_healthy

  uss-queue-redis:
    image: redis:7-alpine
    container_name: uss-queue-redis
    restart: always
    ports:
      - "6391:6379"
    volumes:
      - uss_queue_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - uss-prod

volumes:
  uss_queue_redis_data:
    driver: local

networks:
  uss-prod:
    external: true
    name: prod_uss-prod